### ISSUE TITLE
Is there a way?

### ISSUE THREAD

**Issue by Pipstapee** [westlicht/performer#101]
Is there a way of setting the curve to default at 0v instead of +5v when adding a curve track?
Also...
Can a button be assigned to jump octaves when dialing your notes. I noticed the press of the encoder while on the note page adds a gate to a selected step, could this be changed to course tune, ie octaves?
Sadly I use the HEX files as currently I'm not clued up regarding the code flash method.

**Comment by westlicht** [comment]
Both actually bother me too. Will be fixed with 0.1.25.
