### ISSUE TITLE
note input with launchpad and midi keyboard

### ISSUE THREAD

**Issue by alxsakh** [westlicht/performer#106]
In step sequencer it would be cool if note values was taken when i press step key on launchpad and hit note on midi keyboard.  In note layer now is inposible to record note value from midi with launchpad also.

**Comment by sneak-thief** [comment]
As I mentioned in another issue, this split layout could be very effective:

https://www.youtube.com/watch?v=GVilj3bChHY&feature=youtu.be&t=37

**Comment by westlicht** [comment]
In the current implementation I don't see a good way of doing this. I agree with @sneak-thief that a different layout for launchpad might make sense. But this is part of a larger refactoring.
