### ISSUE TITLE
Curve sequence improvements

### ISSUE THREAD

**Issue by westlicht** [westlicht/performer#108]
- support track linking
- support recording with track linking
- curve variations (probability based) (#45)
- gate patterns (#81)
- fill modes
- offset min/max at the same time (#103)

**Comment by dComposer** [comment]
I love that you have the curve tracks because if I'm only using 2-3 tracks for a song then that gives me a bunch of LFO's to play around with on the leftover tracks. Maybe an extra "curve" type could be a random s&h?

**Comment by westlicht** [comment]
@dComposer if you want random s&h like from a curve track, this is pretty simple to achieve. Select all steps and use the generator to randomize the minimum or maximum value. Then either let it run in periodic (forward/backward/pingpong etc.) or use one of the random modes to advance the sequence for even more randomness. Once you master the controls of the sequencer this can literally be done in a few seconds. No need for a s&h curve type.

**Comment by westlicht** [comment]
Will be part of 0.1.27 release.
