### ISSUE TITLE
Song mode.

### ISSUE THREAD

**Issue by Pipstapee** [westlicht/performer#111]
Is it possible to increase the song mode to more than 16 parts, 64 active parts using the page system?

**Comment by westlicht** [comment]
Did you reach the limit?

**Comment by Pipstapee** [comment]
I like to lay out a song in, intro,Drop,Main,Mid and outtro. Is the limit 16?

**Comment by westlicht** [comment]
Currently yes its 16 slots.

**Comment by dComposer** [comment]
Perhaps something to chew on for down the road: I feel like your performer screensaver (the one with all 16 tracks on the y axis and the steps on the x axis) would make a more intuitive version of song mode. Each cube could be a pattern so you weren't stuck with all tracks having to play the same pattern. Initially that's what I thought this screen was for.

**Comment by westlicht** [comment]
Every song slot can have an arbitrary set of patterns. Read the manual on how to do that. I was initially looking for better visualizations but couldnt get it into the required space/pixel count.

**Comment by westlicht** [comment]
moved of #118
