### ISSUE TITLE
Song page improvements

### ISSUE THREAD

**Issue by westlicht** [westlicht/performer#118]
- extend to 64 slots
- display slots in a table to allow seeing exactly what patterns are triggered on each slot
- move clear function to context menu and rename to init (consistent with other pages)
- better visual feedback when assigning patterns to slots
- add function to duplicate a slot
- do not switch tracks when pressing track buttons (these are used to select patterns for specific tracks)
- add more visual playback information

**Comment by westlicht** [comment]
Will be released with 0.1.30.

**Comment by dComposer** [comment]
Does the inclusion of the time signature mean we're not limited to only writing songs in 4/4 now??

**Comment by westlicht** [comment]
Yes it does. Obviously sequences can still run at a different time division and length. All the measure/bar length are multiples of the time signature now.
