### ISSUE TITLE
Transpose with MIDI note

### ISSUE THREAD

**Issue by dComposer** [westlicht/performer#119]
Another really cool MIDI performance mode would be having the ability to transpose a sequence in real time using a midi controller (like how the microbrute's sequencer reacts to the keyboard).

There could be two flavors:
- simple "chromatic" version: if my project is in the key of C and my sequence is "CCDCECFG" and I press a D on my keyboard then the sequence transposes to "DDEDF#DGA"
- a diatonic mode which would keep the sequence in the project's key, ie, if my sequence is "CCDCECFG" and I press a D on my keyboard then the sequence transposes to "DDEDFDGA" (since there's no F# in the key of C)

Like the arpeggiator, this transposition mode could either be latched or momentary based on a setting.

**Comment by westlicht** [comment]
You can do this using the routing system. Use a key range as the source and the transpose parameter of one or more sequences as the target. If you use the chromatic scale on your sequence you simply transpose by semitones. If you select a scale you transpose within the scale.
