### ISSUE TITLE
Setting up development environment

### ISSUE THREAD

**Issue by james-everitt** [westlicht/performer#120]
Hi Simon,

I've set up the vagrant environment but struggling to find the correct make commands and folder.
From which folder should I be running make commands?
I've tried the root folder, '/src/apps/sequencer', 'build/stm32/release' and a few others.

If you could give some pointers on generating either UPDATE.DAT files or just the hex files that would be great!

Im interested in contributing/customising for firmware for my own needs. Id like to work on launchpad pro integration where the 'User' page is the performer GUI and the note/virtual fader pages are still available over the hardware midi ports.

**Comment by westlicht** [comment]
I have just updated the main README with a guide on how to setup the development system and some overview of the source code structure. Please let me know if there are any obvious mistakes as I did this in a bit of a rush. I hope it's enough to get people going.
