### ISSUE TITLE
MIDI-CV Mono Legato with adjustable glide time

### ISSUE THREAD

**Issue by toneburst** [westlicht/performer#121]
Mono legato mode, with adjustable glide-time for single-voice MIDI to CV channel.

Gate is not retriggered on overlapping MIDI notes, and pitch CV glides to new value over selected time.

Staccato notes operate as normal.

**Comment by toneburst** [comment]
Glide time could also respond to General-MIDI-standard MIDI CCs 5 (Portamento Time) and 68 (Legato mode On/Off).

**Comment by westlicht** [comment]
This would be a good addition. But its a bit tricky, especially if also listening to the midi messages for controlling portamento as they would interfere with manual settings on the track page.

**Comment by toneburst** [comment]
Fair points.

Maybe scrub CC control, then and have portamento time just honour the setting on the Track page.

You could add an option somewhere to turn mono legato/slide on for monophonic parts.

It would either not show up at all for polyphonic parts, or would be "greyed-out".

**Comment by toneburst** [comment]
I don't see a Portamento setting on the Track page, for MIDI/CV track mode in the User Guide.

Do MIDI/CV tracks have a Routing page? If yes, perhaps portamento/slide-time could be routable (with eg a MIDI CC).

**Comment by westlicht** [comment]
Added slide time setting to midi/cv track, same as for note and curve track. This is a routable parameter. Will be released with 0.1.31.
