### ISSUE TITLE
latch mode for switching between layers of the steps page

### ISSUE THREAD

**Issue by madeinspace** [westlicht/performer#123]
I've noticed that I often need to set a gate in the note layer and was wondering if we could implement a latch mode or a quick way to add a gate and comeback to the note layer? does that make sense? ie: holding the note then gate button would take you to the gate layer momentarily so you can add a quick gate and when you release the buttons you automatically return to the note layer. Now that I think about it implementing that for any layers would be really handy and a great workflow improvement :) thanks for considering

**Comment by westlicht** [comment]
First, you can toggle gates in all layers holding step keys and pressing the encoder, no need to switch pages. Second, I don't think this latch mode would improve workflow at all, now you need one hand to hold a button. Much easier to just switch between layers.
