### ISSUE TITLE
sending midi clock from midi out

### ISSUE THREAD

**Issue by indraperkasa** [westlicht/performer#125]
hi Simon,

is it possible to implement send the master tempo bpm pulse thru midi out as a midi clock?
an example case, i would like to use my reverb/delay pedal that can accept midi clock to sync with the delay timing.
by the way really love this sequencer! thanks so much for doing this project.

Indra

**Comment by westlicht** [comment]
Read the manual please. Midi clock is implemented (both in and out). Go to clock setup page to enable it.

**Comment by westlicht** [comment]
And glad to hear you like the sequencer! Thanks!

**Comment by indraperkasa** [comment]
ah sorry about that, i was reading the manual and couldn't find it, i guess i'm gonna re-read again. thanks so much!

**Comment by westlicht** [comment]
Yep, the firmware is quite deep at this point so it's hard to really know all of it's corners. I should start on a video tutorials series because sometimes it feels people do not know some of the coolest workflows available :)

**Comment by indraperkasa** [comment]
ok just found it, i guess i have skipped that midi clock info haha. 
yeah please do make some video tutorials, that would be really nice and helpful, indeed there's so many cool things that i just discovered recently, although been using it for a couple of months 👍 👍
