### ISSUE TITLE
Octave Transpose for MIDI/CV Track

### ISSUE THREAD

**Issue by dComposer** [westlicht/performer#128]
It would be great if the MIDI/CV track had a octave +/- transpose option. I currently use a Beast's Chalkboard between my per|former cv out and my oscillators but it seems like this could be done in the software (and save me 8hp!).

- Now that you've incorporated new midi filtering capabilities, it would be great to be able to drop the lowest note of a chord a few octaves to be used as a bass voice (and vice versa)

- depending on the oscillator I'm using, the arpeggiator tops out while arpeggiating upwards. This way I'd be easily able to knock the arp pattern down a few octaves if I hear this happening in a live setting.

**Comment by westlicht** [comment]
Will be part of 0.1.31 release.

**Comment by westlicht** [comment]
Oh just realized yoy where asking for octave and not transpose parameter.
