### ISSUE TITLE
Curve Track Step Size

### ISSUE THREAD

**Issue by mremusic** [westlicht/performer#133]
It would be a big time-saver if there was a way to spread a curve over multiple steps, set by F5.

e.g. you could have a slow ramp over - let‘s say 8 steps - without having to manually set min and max with each of the following steps, but still had the fine step size for quick modulation (rather than changing the divisor).

**Comment by toneburst** [comment]
This has already been discussed quite extensively. Please search through the existing issues before opening a new one.

**Comment by jackpf** [comment]
I've implemented this in my own build here in case you find it useful: https://github.com/jackpf/performer/pull/8
