### ISSUE TITLE
Midi changes to stay permanently

### ISSUE THREAD

**Issue by luisonly** [westlicht/performer#137]
Hi, is there a way to alter parameters via midi or cv (parameters like "First Step" & "Last Step") and let those modifications stay permanently in the pattern?

**Comment by westlicht** [comment]
No, the main purpose of the routing system is live performance or experimentation. It's not really meant to be used for "programming" duties. Does this answer the question?

**Comment by luisonly** [comment]
Yes it does, very much. Thanks for your time Simon.

**Comment by westlicht** [comment]
Your welcome!
