### ISSUE TITLE
Tuning utility idea

### ISSUE THREAD

**Issue by mkl-b** [westlicht/performer#142]
Hello
I've just built this seq. Its wonderful piece of hardware, thank you for making it free and open :)
Have you thought about adding tuning utility tool like in O_c, in "references" app.
It would be really helpful :)
Thanks

**Comment by westlicht** [comment]
This is a bit tricky because the ADC is not sampled at a high enough frequency to measure cycles. So this is not something I plan to implement, sorry. I guess using a cheapo guitar tuner is still kind of the easiest thing for tuning.
