### ISSUE TITLE
feature request: arps for cv tracks

### ISSUE THREAD

**Issue by froschmett** [westlicht/performer#143]
Hi,

wouldn't it be possible to make arps available on cv tracks? Like defining a root note, chord type and arp mode? Happy to hear some feedback :).

**Comment by toneburst** [comment]
There's already an arpeggiator for CV tracks.
Please look in the [manual](https://westlicht.github.io/performer/manual/) before submitting a feature-request.

**Comment by westlicht** [comment]
@froschmett did you mean on normal note tracks? In that case no, there is no plan to support that. As @toneburst mentioned there is a pretty powerful arp available on MIDI/CV tracks.

**Comment by froschmett** [comment]
Hey,
I read the manual, thanks for mentioning... What if I don't use MIDI to CV?

Anyway, I am using the 2hp arp module to achieve the effect I need.

**Comment by westlicht** [comment]
Ok, that's great then. MIDI/CV is meant for studio use and to be able to play some voices live, where the arp makes a lot of sense. You can configure the sequencer to take in CV/Gate on the CV inputs and use that as "virtual MIDI" on a MIDI/CV track, so essentially you'd have the option to run this from some other source than a MIDI keyboard.

**Comment by froschmett** [comment]
Hey,
ok, I will test that, thanks Westlicht :)!

**Comment by froschmett** [comment]
Hmm,

tried it, cant get that to work, maybe you can provide an example? Would be nice, thanks a lot... :)
