### ISSUE TITLE
double tap SHIFT too fast?

### ISSUE THREAD

**Issue by mopoco-git** [westlicht/performer#144]
Hi there,
i'm new to the performer and absolutely loving it so far!

on the STEPS page: i find the double tap SHIFT function to select all steps quite hard
to achieve. 
could (and should?) the recognition of the double tap be set so that we can double 
tap with longer intervalls? (it generally makes me a bit nervous, especially when i'm working on slower sequences...)

**Comment by froschmett** [comment]
2nd that, you got to be real fast to achieve selections with 2x shift...

**Comment by westlicht** [comment]
Ok, will experiment with slower double taps, i got kind of used to the fast ones :)

**Comment by mopoco-git** [comment]
awesome! and since afaik there's no single-shift-function (only hold-shift functions) i guess you
could make the double tap recognition basically reeeeeeally slow and your fast ones will still get recognized? though an intervall of one second might be enough, even for the most chilled out amongst us  :)

**Comment by westlicht** [comment]
Double tap interval will be increased by 50% in 0.1.33 release.
