### ISSUE TITLE
MIDI output issues

### ISSUE THREAD

**Issue by mongrol** [westlicht/performer#148]
v1.32: Midi output only sends data when the note's are C#4 and upwards. Anything from C4 (0v) or below results in nothing being sent.
In addition midi-in to midi-out doesn't pass through no matter what the note or whether Play mode is activated or not unlike midi-in to CV out which works fine.

**Comment by mongrol** [comment]
Further testing reveals it's a velocity issue. The note data is being sent but with velocity of zero.

**Comment by westlicht** [comment]
> In addition midi-in to midi-out doesn't pass through no matter what the note or whether Play mode is activated or not unlike midi-in to CV out which works fine.

What do you mean exactly?

**Comment by rheslip** [comment]
Related enhancement would be to pass MIDI thru when step recording for audible feedback when a MIDI synth is attached.

**Comment by westlicht** [comment]
Implemented monitoring forwarding to midi output. Will be released with 0.1.34.
