### ISSUE TITLE
New "note on" does not generate a new gate

### ISSUE THREAD

**Issue by smootmather** [westlicht/performer#149]
Hi Simon, maybe i´m missing something.
PerFormer does not generate a new "Gate" when receiving a new "Note On" until last "Note On" is released. Midimonitor shows a new "NOTE ON" 
This is in MIDITrack Mode and on other tracks receiving Midi.

Another question: is it possible to switch off midi-receiving for chosen tracks? Problem is when playing an arpegiator via midi any other chosen track is receiving midi and is playing not the sequence which is programmed.

Kind Regards Manuel

**Comment by smootmather** [comment]
Sorry, i got it. Retrigger in Midi track was not enabled.

**Comment by westlicht** [comment]
Closing in favor of #155
