### ISSUE TITLE
Wrong Notes in Scales

### ISSUE THREAD

**Issue by MaxiMars73** [westlicht/performer#150]
On „A Minor“ Pentatonic I get the Notes A#, C, D#, F, G. 
On „A Minor“ I get the Notes A#, C, D, D#, F, G, G#. The Root Note is even not included. If the Root Note is C then the right notes are chosen. Other scales also have this odd behaviour. It seems that the transpose behaviour does it by the wrong amount of halfsteps.

**Comment by westlicht** [comment]
Yes its a bug, already fixed in #147 but not released yet. Will do a release this weekend.

**Comment by smootmather** [comment]
think this is what louis tried to describe in #41

**Comment by westlicht** [comment]
Sorry, release got delayed. I'm preparing a release now. Closing this.
