### ISSUE TITLE
contolling multiple sequencer

### ISSUE THREAD

**Issue by mrtisit** [westlicht/performer#152]
Is it possible to control multiple sequencer with one launchpad? 
Maybe with a hub

**Comment by toneburst** [comment]
USB has hosts and devices. It's possible to connect multiple devices to a single host, but not to connect a single device to multiple hosts.

Per|Former is a host, the Launchpad is a device, so you could potentially connect multiple Launchpads to a single Per|Former (using a USB hub), but you can't connect a single Launchpad to more than one host, even with a hub.

**Comment by westlicht** [comment]
Thanks for answering @toneburst. Its not possible unless you would have a middleman acting as two launchpads :)
