### ISSUE TITLE
No midi lower than D#0

### ISSUE THREAD

**Issue by smootmather** [westlicht/performer#156]
Hi Simon, not sure if it depends on the update. but there´s no midi send with notes lower then D#0

regards manuel

**Comment by westlicht** [comment]
Not sure what you mean but I can easily output the full range.

- C0 on the sequencer (0 volts) represents MIDI C3 (decimal 60)
- The lowest representable note in MIDI is C-2 (decimal 0) which corresponds to C-5 (-5 volts) on the sequencer.
- The highest representable note in MIDI is G8 (decimal 127) which corresponds to G5 (> 5 volts) on the sequencer. The highest note that can be output physically on the sequencer is C8 (5 volts) but internally the sequencer can generate notes greater than that, if a suitable scale is selected.

I've just tested this and all seems fine, note sure how you came up with D#0 as the lowest note.

**Comment by smootmather** [comment]
Hello Simon, 
this is a videolink which describes my problem. https://youtu.be/pnCLEVi06qQ
Midi is sent via USB to MiniBrute. Problem also occurs  when midi is send via midi. If i take another midisource, lower notes work on the MiniBrute. 
Hope that helps. Maybe something is wrong with my Device, but another one i built for a friend had the same problem... 
Kind Regards. Manuel 

---- Simon Kallweit schrieb ----

**Comment by westlicht** [comment]
Really weird. I tested with a midi monitoring application to inspect the messages actually sent on the wire and it's all good. What's your midi output setting on performer?

**Comment by smootmather** [comment]
I also tried with another Synth to receive midi. 

---- Simon Kallweit schrieb ----

**Comment by smootmather** [comment]
Hi Simon,  today i found that i have to set velocity to min. 1 that midi is send C0. If velocity is set to track than only notes  above C0 is getting out. 
Hope that's helps. 
Regards Manuel

**Comment by mike-kelly** [comment]
I can confirm this issue. To clarify @smootmather 's comment: 
In the midiout page, if Vel. Source is set to a track, the midi out range is limited. In my case no midi out notes are emitted below pitch C#0.  A workaround is to set a **fixed value** for Vel. Source instead of a **track**. Scroll past the track options and choose a fixed velocity of 1 or above.
