### ISSUE TITLE
Routing: Tempo <20

### ISSUE THREAD

**Issue by Volod3Mir** [westlicht/performer#158]
Hi, is it possible to have minimum Tempo destination under routings be less than 20?

Thanks

**Comment by westlicht** [comment]
What should the minimum be in your opinion?

**Comment by Volod3Mir** [comment]
For modulation purposes I would like to be able to set it to zero.

**Comment by cornil-m** [comment]
And to 999 and not 500 <3

**Comment by westlicht** [comment]
Zero is tricky, as this essentially means the sequencer is stopped introducing some annoying edge cases. But a range 1..1000 is possible and would make sense as it's also what can be set on the project page.

**Comment by Volod3Mir** [comment]
Maybe 0.1 then?

**Comment by westlicht** [comment]
New range is 1-1000.
Will be released with 0.1.34
