### ISSUE TITLE
16 MidiOuts

### ISSUE THREAD

**Issue by Volod3Mir** [westlicht/performer#159]
Since we can mix and match gate and pitch tracks, can we have 16 midi outputs instead of 8, to utilize all channels?

Thanks!

**Comment by westlicht** [comment]
I don't get this, I think 8 outputs are more than enough given that there are only 8 tracks in the sequencer. Typically you need 1 or more sequencer tracks for one MIDI output. Having 16 outputs would mean that tracks are assigned to more than one MIDI output.

**Comment by Volod3Mir** [comment]
But that is ok because you can have 64 unique combinations of gates from one track and pitch from another...

**Comment by westlicht** [comment]
Will be released with 0.1.34
