### ISSUE TITLE
Fill unmute muted tracks 

### ISSUE THREAD

**Issue by cornil-m** [westlicht/performer#161]
Would it be possible that the fill option doesn’t trigger tracks that are muted?

**Comment by westlicht** [comment]
I guess this might be an option somewhere. I personally prefer having fill active on muted tracks too. It allows me to temporally bring in elements on muted tracks.

**Comment by toneburst** [comment]
+1 for this, too. I was thinking exactly the same just the other day!

Could there be a setting somewhere to toggle current/suggested behaviour?

It could be a per-Track, or even per-Sequence setting, rather than a global thing.

**Comment by westlicht** [comment]
Not sure I'd want it as a per track feature. It's one more option that probably is in the way most of the time. A global setting could make sense if I introduce a new settings page. See #85

**Comment by westlicht** [comment]
Added _Fill Muted_ option to note tracks. Will be released with 0.1.37.
