### ISSUE TITLE
Updated to v0.1.34 now all project files invalid

### ISSUE THREAD

**Issue by kidko** [westlicht/performer#168]
I just took the brand new v0.1.34 update, which updated successfully from the bootloader. Loading any project from the project page is returning "Project File Invalid" when I try to load.

repro:
Navigate to project page.
Choose Load from contextual menu
scroll to project and click encoder
It says "are you sure?" and I hit yes.
See loading graphic then receive dialog window that says INVALID PROJECT FILE
Nothing is loaded

Edit: Creating a new project and saving then loading it works fine. Doing this, I tried an old one again and noticed it does seem to load something, since I noticed the new MIDI feature which consumes notes to a MIDI track stopped happening after I'd attempted to load an old project. Loading the new one afterwards re-enabled the new MIDI feature (which rocks, this is the reason I updated. So useful!)

**Comment by westlicht** [comment]
This is a nasty one, took me a while to figure out. The good thing is I should have a fix soon.

**Comment by westlicht** [comment]
Fix coming with 0.1.35
