### ISSUE TITLE
changing scale of sequence changes its notes unexpectedly?

### ISSUE THREAD

**Issue by mopoco-git** [westlicht/performer#169]
not sure if this is intended behaviour:
- set project scale to 'semitones'
- set project root note to 'A'
- set all track notes to 'A0'
---------irritation:
- when changing the sequence scale to something other than 'default'
all track notes shift, sometimes by octaves (i.e. they are other than 'A0')
- i'd expect that those 'A's (which correspond to the project root note)
would stay in place.
(- though i wouldn't be that surprised in case the track notes would be set to
a different note than the project root and changing the sequence scale would
kick them in the right place within a given sequence scale...)

**Comment by westlicht** [comment]
This is expected behaviour with _voltage tables_. Depending on the scale there is a different number of notes. This leads to the fact that note number 12 in _semitone_ scale is the octave, but note number 12 in a major scale is an octave plus 5 notes along the major scale. Hope that makes sense.
