### ISSUE TITLE
Feature Request: Midi CC to CV

### ISSUE THREAD

**Issue by mongrol** [westlicht/performer#171]
Can we have the ability to use MIDICV tracks to convert a specified CC value to a CV voltage?

**Comment by westlicht** [comment]
This does not really fit well into the existing MIDI/CV track options. I think you can achieve this using a workaround:

- have a normal note track with a custom scale using small voltage steps playing the same step
- reduce the divisor so the sequence plays/updates quickly
- assign a MIDI CV controller to the transpose parameter
