### ISSUE TITLE
Option to turn off automatic midi note input 

### ISSUE THREAD

**Issue by luisonly** [westlicht/performer#174]
Hi! My performer is hooked via midi to some parts of my studio which have midi notes flowing. Sometimes when im working on a sequence and editing it, if I scroll pass the "NOTE" part It will take the streaming midi notes and change the notes in my sequence. I see the advantage of being able to select a note and directly record a note via my midi controller, but is it possible to add a menu option to override this? Thank you very much!

**Comment by westlicht** [comment]
I guess that would be a good addition to a new settings page. See #85
