### ISSUE TITLE
Feature request: track mutes in song mode

### ISSUE THREAD

**Issue by nickthekick** [westlicht/performer#178]
a feature where you can add track mutes/no pattern in song mode would be great!

**Comment by westlicht** [comment]
I think it's easy enough to just use an empty pattern, no?

**Comment by nickthekick** [comment]
I’m using empty patterns now but for overview purposes it gets kind of messy. I think an x or - would make it way easier to see what parts that are muted. 


//Nick

**Comment by westlicht** [comment]
I see. This feature would require some change to the data layout unfortunately as the pattern is stored in 4 bits now. I'll keep the issue open but it's not high prio

**Comment by nickthekick** [comment]
Ok :)

//Nick

**Comment by westlicht** [comment]
I have a partial implementation of this but did run into a bit of an issue. Performers song mode is also a performance feature to quickly chain some patterns. For this usecase one wants to control mutes manually. Now that song slots contain that information, it will basically set the slot's mutes when the slot is changed, overriding the current mute. So for example, if I quickly chain two patterns and mute one or several tracks, whenever the song slot changes the patterns change and the mutes are disabled. This is annoying. One option would be to check if there are any mutes set on a track across all slots in the song. If there are not, we simply don't set the mute state allowing song mode to be used as a performance feature. Once there is a single mute state defined on a track in the song, we always set the mute state when switching slots. But this still can be a bit unexpected I think. So not sure how to exactly tackle this.

**Comment by nickthekick** [comment]
Yeah I understand. But if it’s mutes per pattern they could be linked right?  I’m thinking that it’s quite a fast workflow to duplicate pattern and mute what you want and duplicate again and change what you want. But maybe that’s my workflow only

//Nick

**Comment by westlicht** [comment]
Will be part of 0.1.36 release.

**Comment by nickthekick** [comment]
Sweet! Good work!

//Nick

**Comment by westlicht** [comment]
Let me know how it works for you.
