### ISSUE TITLE
Live CV output?

### ISSUE THREAD

**Issue by theotteryears** [westlicht/performer#186]
When a track is set to Curve, does changing the value update the CV live? this would be useful if it could happen

**Comment by westlicht** [comment]
@theotteryears If you mean changing the curve value (min,max,shape etc) then yes it's updated in realtime.

**Comment by theotteryears** [comment]
maybe im doing something wrong then, but this only works when the sequencer is running. Would be good if it could happen while stopped too for setting the correct cv value for other modules.

**Comment by westlicht** [comment]
Ah now I get it!

**Comment by theotteryears** [comment]
:) sorry I should have been clearer! (also thank you for such a wonderful sequencer)

**Comment by westlicht** [comment]
Thanks! I have to give that idea some thought.

**Comment by westlicht** [comment]
Will be part of 0.1.36 release.
