### ISSUE TITLE
Option to fire the RESET OUT slightly later than the last clock pulse

### ISSUE THREAD

**Issue by theotteryears** [westlicht/performer#188]
it would be useful to have an option to disable the reset out getting fired when the sequencer is stopped.

also would be nice to have a new button combo which you could manually send a reset out from.

**Comment by westlicht** [comment]
If you don't want a reset/run signal, you could just not connect it. An option would be to add a _Disabled_ mode to _Output Mode_ on the clock page. But without the manual reset feature that would be rather pointless. Or do I miss something here?

**Comment by theotteryears** [comment]
Yeah don’t worry! I mean to close this sorry
