### ISSUE TITLE
Cv\Gate input issue

### ISSUE THREAD

**Issue by Dunk303** [westlicht/performer#194]
Lately I'm using the cv\gate input option a lot to input notes in a sequence. This is very fast and natural way to write down melodies, however I've found that every few notes (let's say one in ten notes) the sequencer take the adjacent flat note for a moment and then switch to the right one. Of course if recording is enabled the wrong note get recorded in a step.
I think that is due to the devices wich outputs the cv signal, while the gate is already high the cv is still rising to it's final value.
A simply fix for this should be to add the option to read the cv input a few ms after the gate, so the external cv should have reached it's value. 
I'm guessing that a 2-5ms delay should be more than adeguate to solve the issue without being noticeable. 
Any thought about this? 
:)

**Comment by westlicht** [comment]
Added a 5ms delay. Will be released with 0.1.37.
