### ISSUE TITLE
Clarify launchpad model compatibility in documentation

### ISSUE THREAD

**Issue by stansanders** [westlicht/performer#20]
Most references simply say "Launchpad" without specifying that Launchpad (NOVLPD01 / 0x000e)  will not work.  Should specify "Launchpad Mini" or others as compatibility is confirmed.

**Comment by stansanders** [comment]
Also clarification on whether it's Launchpad Mini II or Launchpad Mini, or if both are supported.  Searches for the novation vendor id (0x1235) on https://devicehunt.com/search/type/usb/vendor/1235/device/any and https://www.the-sz.com/products/usbid/index.php?v=1235&p=&n= don't show devices for id 0x0035 or 0x0036.  For users purchasing a launchpad to use with their sequencer this information would be very helpful to have.

**Comment by toneburst** [comment]
I think LP Mini and Mini Mk.2 are functionally identical, so both should work, assuming both are recognised by their IDs.

**Comment by toneburst** [comment]
Ah, now I know how to get into Pattern mode. I had discovered button 8 can be used to mute tracks, but not that it also had other functions.

Great work, Simon!
