### ISSUE TITLE
Expanders?

### ISSUE THREAD

**Issue by theotteryears** [westlicht/performer#206]
Long shot - but is there a plan for any expanders? I like the sequencer a lot and want more than 8 tracks!

**Comment by theotteryears** [comment]
alternatively - is there a way to clock a second Performer so the master clock of the first (384ppqn) is upheld? or would 24ppqn be sufficient between the 2?

**Comment by westlicht** [comment]
There are no plans for expanders at this time.

You can clock your performer any way you want. The input clock resolution is always multiplied up to the internal 192ppqn resolution.
