### ISSUE TITLE
Mark gates when using a curve track on the OVERVIEW screen

### ISSUE THREAD

**Issue by theotteryears** [westlicht/performer#210]
would be useful to see when they are occurring

**Comment by westlicht** [comment]
I don't think there is enough space on that page to add gates for curve tracks. The display has 64 pixels in height, leaving 8 for each track. Remove 1 for the spacing, you have 7 pixels for the curve. Adding gate information would remove 2 pixels (1 for the gates, 1 for the space) leaving 5 pixels for the curve visualization. So I don't think adding gate information there is that useful. Think of it from another perspective, there could also be a request to visualize retriggers, slides and whatnot. That's not really the point of the overview page anymore. So I think I'll close this one.
