### ISSUE TITLE
Each track gets its own pattern sequencer/song page

### ISSUE THREAD

**Issue by theotteryears** [westlicht/performer#213]
Not sure if this is possible but I thought it would be great if each track could have its own song page - like a playlist type thing...

Track 1 plays pattern 1, pattern 2, pattern 3, pattern 4
Track 2 plays pattern 1, pattern 2 (repeated)

I often want a track to be moving through some patterns whilst the others keep on the same one.

**Comment by westlicht** [comment]
This functionality is not matching well with the current data model, so I don't see it being implemented anytime soon. I also think it's easy enough to setup a song/chain to do just that.
