### ISSUE TITLE
Fill on Performer page to affect Curve tracks

### ISSUE THREAD

**Issue by theotteryears** [westlicht/performer#215]
Please - I need the gate to repeated fire, but also the CV value at step one to be held at the same time.

**Comment by westlicht** [comment]
So you are asking for a new fill mode then?

**Comment by theotteryears** [comment]
maybe yes

**Comment by westlicht** [comment]
The curve track focuses on curves, thus the fill modes do as well. It's better to use a note track (even for drums) to get more control over gates.
