### ISSUE TITLE
Permanent changes via midi

### ISSUE THREAD

**Issue by luisonly** [westlicht/performer#217]
I know this has been addressed before but anyways... I make a lot of polyrhytmic stuff and changing the beginning and end of each track is very useful for this. Using lemur I am able to change very quickly and even randomly the beg/end points of any given track(s) and many times coming to very interesting results which ID ABSOLUTELY LOVE to make permanent in a given pattern. Is there any chance changes done via midi stay permanent? I know this can be made manually but it is a inspiration killer for me. I tried doing it manually and it is very very boring. 

Thank you for your amazing work!
Luis.

**Comment by westlicht** [comment]
The routing system is more intended as a live feature. So I'm afraid the answer is no. But, why don't you use the quick access to first/last step on the sequencer itself. Hold `PAGE` then press `S9` or `S10` to enter first/last step quick edit on the sequence edit page. Then you either use the step buttons to select the step or just twist the encoder. This is super quick and I use it all the time to come up with nice variations. And the changes are permanent.
