### ISSUE TITLE
New feature? destiny Routing: step forward

### ISSUE THREAD

**Issue by franq87** [westlicht/performer#219]
Could it be possible this feature? routing a track that each step could be externally triggered so I can make a short of sample&hold and use that track like a quantizer?

**Comment by MDCusack** [comment]
Weird, i was literally looking to see if that was possible last night. Adding the option to unlink a track from the main clock and only have it proceed steps forward upon receiving a 5v hit from a CV input setup via routings would be very cool.

**Comment by franq87** [comment]
@MDCusack yeah It would be very cool, let's see if it's possible

**Comment by napoleonthegreat94** [comment]
@MDCusack i would reaally like to see that too! but then, how would the song mode work with different clocks going on?

**Comment by westlicht** [comment]
I can see the appeal of such a feature but the current architecture is not really suited to implement this and would mean ugly hacks. So I'm afraid this is not going to happen, sorry.
