### ISSUE TITLE
Midi CC to CV

### ISSUE THREAD

**Issue by kurtjoy** [westlicht/performer#221]
Is this possible? The korg Nano studio works fantastic with the performer. But id love to get the rotaries and XY pad sending CV to modules from Midi CC.

**Comment by westlicht** [comment]
I added a new _Offset_ parameter to the curve tracks (which is similar to _Transpose_ on a note track). This new parameter is routable, meaning you can map any midi or CV input to adjust the offset of a curve CV output in realtime. Now in addition to just mapping a midi knob to a CV output, you can also use it to adjust the offset of a running sequence, which is even cooler IMHO.

This will be part of the 0.1.37 release.
