### ISSUE TITLE
New feature Request - 8x8

### ISSUE THREAD

**Issue by m0dernchair** [westlicht/performer#223]
Would it be possible to have more than 16 patterns per track in the future? It would be great if there was 8 x 8 tracks of 16 sequencers to a project. Is this something memory would prohibit from happening?

**Comment by westlicht** [comment]
There is not enough memory for that unfortunately.

**Comment by westlicht** [comment]
There is not enough memory for that unfortunately.

**Comment by westlicht** [comment]
There is not enough memory for that unfortunately.

**Comment by westlicht** [comment]
There is not enough memory for that unfortunately.

**Comment by westlicht** [comment]
There is not enough memory for that unfortunately.
