### ISSUE TITLE
Exotic run modes 

### ISSUE THREAD

**Issue by Materia-Oscura** [westlicht/performer#225]
Hey, 
Watching a René 2 video i find very interesting the way you can alter the playing order of a sequence with some "snake" patterns
It can also be abused for monophonic arpeggiation 👍 
Would it be possible to implement this kind function to the performer?

**Comment by westlicht** [comment]
Can you be more specific? Also, how would this translate to sequences with an odd number of steps?

**Comment by westlicht** [comment]
Closing this as there is no feedback from anybody, so probably not super important.
