### ISSUE TITLE
Feature request: Muting CV and Gate separately

### ISSUE THREAD

**Issue by Gras-duinen** [westlicht/performer#227]
Hi!

Would it be possible to implement a change so you can mute either the cv or the gate of a track? While the other keep running?

Thanks in advance!

**Comment by westlicht** [comment]
I don't think there is a good way to offer that function. Is this for note or curve track?

**Comment by westlicht** [comment]
There is already an option to always update the CV output, even if the track is muted. The other way (keeping cv while still outputting gates) could be achieved with an external sample and hold module ..
