### ISSUE TITLE
MIDI CV step recording options

### ISSUE THREAD

**Issue by natedey** [westlicht/performer#228]
Hi there,
Recently got the Performer, and my goodness, what an incredible module!!!
I have a suggestion that might improve MIDI step sequencing
The Mutable Instruments Anushri desktop synth has a step sequencer that can recognize pitch bend and mod wheel movements to manipulate the step recording. On that box, pitch wheel movement (magnitude and direction don't matter) adds glide to the step, mod wheel movement adds an accent to the step. I always thought that was less useful than having rest / tie assigned to pitch and mod. 
Would it be possible to have hard-coded or assignable options to bend/mod/or other CC to be able to input a more nuanced sequence completely on the controller? Thanks!

**Comment by westlicht** [comment]
Very good idea. It will be part of the 0.1.37 release.

**Comment by natedey** [comment]
awesome! Thanks Simon
