### ISSUE TITLE
Ability to init one layer data  only

### ISSUE THREAD

**Issue by shsCT** [westlicht/performer#230]
Would love the ability to init say, just the note range layer or a probability layer, rather than globally initializing all step info at once. Thanks!

**Comment by captainhooke88** [comment]
Just from the top of my head you might be able to do that with The generate function. Go to the function you want to Init and press shift+page and then gen on screen and just leave all values at 0 and commit?

**Comment by shsCT** [comment]
Hmm interesting! Thanks - Will have a go at that. Might still be useful to have a quick one-push way to clean out existing ranges variations/probabilities in the heat of a live performance though. But boy do I love this sequencer!

**Comment by westlicht** [comment]
I don't see a good way to put the functionality into the `INIT` function. Instead I opted to add a `Init Layer` generator for that function. The problem with using other generators is that it's not necessarily setting the layer to the _default value_.

Will be part of the 0.1.37 release.
