### ISSUE TITLE
Feature request: Doubletap in notes mode to toggle gates

### ISSUE THREAD

**Issue by rolfjack** [westlicht/performer#232]
Performer + launchpad is such a killer combo. But there is one thing thing that I would really wish for: The possibility to toggling gates on/off in notes mode via a double press (or a long press) on a pad.

When editing a melodic sequence it is super convenient that one can pick 8 notes in scale or semitones. However, it is quite cumbersome to have to switch to gate mode, toggle gate status, return to note mode and set a note in order to make a small change to the rythm. It would be so much more intuitive to simply double tapping a note to change the gate value on/off.

It is worth considering if long pressing one or more notes simultaneously could be used to make a tie or something. But adding some flexibility in how notes and gates can be edited on the notes page would make editing significantly faster and more intuitive.

Note: I also left this comment in the thread about follow mode, but toggling gates on/off in note more is really a separate request, so I thought I would give it its own thread as well.

**Comment by westlicht** [comment]
Double press for toggling gates will be part of 0.1.38 release.
