### ISSUE TITLE
Feature request: changing # of voices in a MIDI/CV track automatically sets subsequent tracks

### ISSUE THREAD

**Issue by natedey** [westlicht/performer#236]
I'm still getting my footing with the module, but it is not obvious from the manual that if you increase the voices in MIDI/CV track, that you also have to set the subsequent tracks to MIDI/CV and also make sure those subsequent channels are routed to the additional voices. It would be phresssshhh to have a menu item "auto routing" that would automatically set this up. I think having this completely automated would be disaster though because it would possibly erase child tracks that were populated with sequences or curves! 

Once I figured this out and got it rolling last night tho, I was in Eurorack chord heaven. :)

**Comment by westlicht** [comment]
Right now I don't have time to add this. Because this is mostly a one time setup procedure, I don't think that's a huge issue. Adding to backlog.
