### ISSUE TITLE
Feature request: Drum Track

### ISSUE THREAD

**Issue by dComposer** [westlicht/performer#239]
When programming drums I end up using a bunch of precious tracks just for their gate outputs. What I propose is a "Drum Track" which still uses the gate output but also turns the cv output into something that can independently shoot out it's own 5V gate. It could act like a normal note track with F1 sending you into the GATE1 page and F4 sending you into the GATE2 page (replacing the notes page). It's minor but it would let me consolidate drum tracks and use the outputs more efficiently.

**Comment by westlicht** [comment]
This is not easily doable unfortunately. I would suggest you make your drums more interesting by using the CV out for some modulation :D

**Comment by natedey** [comment]
Couldn't you just use a curve track with simplistic settings for this???
