### ISSUE TITLE
VCVRack port for simulator

### ISSUE THREAD

**Issue by gbrandt1** [westlicht/performer#24]
Hi Simon,
Have you considered adding a build/port of the simulator for VCVRack? there are already many sequencers available there but people love skeuomorphic interfaces and i think per|former would be a hugely popular module there.
Cheers,
southpole

**Comment by westlicht** [comment]
I thought about it but it will be difficult to control the sequencer. I pretty much hijack all of the keyboard and mouse scrolling to control the simulator.
