### ISSUE TITLE
Suggestion: Page numbers in manual

### ISSUE THREAD

**Issue by rolfjack** [westlicht/performer#242]
Navigating in the manual can be challenging because there are no page numbers. 
I manually added to every page and on the index and it was a huge help.

So it would be great for page numbers to be added to the pdf version of the manual so I/we do not have to add them manually whenever there is an update.

Thank you for all your great work.

**Comment by rolfjack** [comment]
Hi. I am enjoying the v39 firmware manual, but once more have to enter pagenumbers manually in the PDF version.

Any chance of adding page numbers to the manual?

**Comment by westlicht** [comment]
Unfortunately with the current toolchain to convert markdown to PDF it's not possible to add page numbers.
