### ISSUE TITLE
Setting the root note per track or global

### ISSUE THREAD

**Issue by lanceblaise** [westlicht/performer#244]
I use a fair amount of digital oscillators. I always need to set the note to C +4 in order for it to sound right. As a work around I have saved empty tracks all at C +4. Is this the only way to do this or is there a better easier way. Sorry if this is not posted in the correct place. Thank you

**Comment by westlicht** [comment]
You can use the _Octave_ or _Transpose_ option on the track page to offset the note value for a track.
