### ISSUE TITLE
Routing Target: Gate & CV output assigment (Layout page)

### ISSUE THREAD

**Issue by hotelbachelard** [westlicht/performer#257]
Looking more into the options on the Layout Page, particularly the Gate and CV output assignments. Since it's an option on the sequencer, I wonder if it might be possible set Gate & CV Output as a Routing target, so you can use a CV input or another track to automate the switching of gates and cvs coming out of each track.  That could lead to some really unexpected modulation, especially if you route Curve CV to the output of a Note track (which I just tried to do manually).

**Comment by westlicht** [comment]
It's not something that is feasible to do and probably would lead to more confusion than anything else :)
