### ISSUE TITLE
Launchpad: Show empty and non-empty patterns on Pattern page

### ISSUE THREAD

**Issue by toneburst** [westlicht/performer#26]
It's currently not possible to tell if a pattern on the Pattern-select page is empty or not.
Suggest lighting non-empty patterns in a dimmed colour, leaving empty patterns unlit.

**Comment by westlicht** [comment]
This is a good suggestion, however, I have to think what exactly qualifies as an _empty_ sequence. But probably it would just be it's initial state.

**Comment by toneburst** [comment]
Cool. I think one with no steps set to "on" for Note tracks.
Not sure what would define an "empty" Curve track.
