### ISSUE TITLE
Undo request

### ISSUE THREAD

**Issue by hotelbachelard** [westlicht/performer#260]
Would love to be able to undo actions. There are times I edit a bunch of notes at a time and it sounds terrible and want to revert back to the previous state of things.

**Comment by napoleonthegreat94** [comment]
This would be a realy nice feature, i wonder if it is possible

**Comment by westlicht** [comment]
Unfortunately it's not something I can do with the current memory restrictions. As mentioned before, the snapshot system can be used to easily set a savepoint to easily jump back to.

**Comment by napoleonthegreat94** [comment]
Fair enough, thanks for looking into it nonetheless
