### ISSUE TITLE
Bug? transport cursor gets choppy on Curve track when muted

### ISSUE THREAD

**Issue by hotelbachelard** [westlicht/performer#261]
Very minor issue that doesn't exactly affect performance, but I just noticed that when I mute a Curve track, the play cursor gets choppy, and goes back to smooth operation when unmuted. Happens in both Free and Aligned mode. 

Short video: 
https://www.dropbox.com/s/0f5b3auu4k6t8em/20201205_205032.mp4?dl=0

Again, doesn't affect playback as far as I can tell, but thought I'd make a record of it.

**Comment by westlicht** [comment]
Fix will be released with 0.1.40 release.
