### ISSUE TITLE
Pre Listen Note

### ISSUE THREAD

**Issue by CedreLo** [westlicht/performer#262]
Hi,

A possibility to prelisten the note/step entered without having to run the sequencer could be great.

for example with a combiner's key like by clicking the step/note and play

**Comment by westlicht** [comment]
On the sequence edit page make sure to be on the note layer. Selecting steps should play them if the sequencer is stopped. Changing note values will play them as well.

**Comment by CedreLo** [comment]
oh great!!! thanks
