### ISSUE TITLE
Doubletap to toggle gates not only for launchpad

### ISSUE THREAD

**Issue by CedreLo** [westlicht/performer#264]
Hi,

It could be great to have the launchpad function "Doubletap to toggle gates" not only for launchpad.

**Comment by westlicht** [comment]
You can hold any number of step keys and press the encoder to toggle gates when on other layers. Double tap is probably unused right now, so it might be an option but I don't really like redundancy and the existing functionality is probably better due to working on multiple steps.

**Comment by CedreLo** [comment]
Encoder press to toggle gate. Great.

Thanks
