### ISSUE TITLE
Autoload Project Save

### ISSUE THREAD

**Issue by CedreLo** [westlicht/performer#266]
Just a little issue, when the auto load last project is enable, when we want to save it doesn't select it.

**Comment by westlicht** [comment]
Showing the slot selection when saving the auto loaded project is on purpose, you might not intend to overwrite it when coming back to the sequencer after a while. However, it didn't pre-select the slot it was loaded from which is now fixed.

Going to be released with 0.1.40.

**Comment by CedreLo** [comment]
Thanks.
