### ISSUE TITLE
Fill Active on muted tracks

### ISSUE THREAD

**Issue by CedreLo** [westlicht/performer#267]
When we use Fill in perf page, it active the gate even on muted tracks.

**Comment by westlicht** [comment]
There is an option to disable that. You should start reading the manual! :)

**Comment by CedreLo** [comment]
Hi

I read it. 

And i have Fill Muted set to YES in Track Page.

Is there adoption option ?

**Comment by westlicht** [comment]
if you don't want fill on muted tracks you have set _Fill Muted_ to _No_.

**Comment by CedreLo** [comment]
ok. Perfect.

Thanks
