### ISSUE TITLE
CV out as GATE

### ISSUE THREAD

**Issue by CedreLo** [westlicht/performer#268]
Hi,

I would like to sequence a hi Hat module with two input CH and OH, but I don't want to use 2 tracks.

A new track type (2 gate) can be useful.

Maybe I can use the CV out as a gate with curve track and a square shape ? 

But a new track type would be better, the performer will become a 16 trigger/gate sequencer!

Thanks

**Comment by westlicht** [comment]
This has come up before and it's not on my list of improvements. I'd rather look into using the CV output for modulating the sound and using two tracks.
