### ISSUE TITLE
Problems using routing for Record/play with foot pedal

### ISSUE THREAD

**Issue by rolfjack** [westlicht/performer#273]
To free up my hands I tried using a foot pedal from my keyboard to stop/start recording. Using the learn feature it identified CC=64 as the source, and having min=off allowed me to control record from my foot pedal via Deepmind12.

**BUT: Setting up a route to control RECORD means that manual control via the interface is no longer possible. 
Now the ONLY way to record is by using the foot pedal.**

For a number of reasons I find that this does not work well in practice.

It would be nice if the routing could function as a toggle switch in PARALLEL with the normal way of using the play/record features.

Thanks, Rolf

**Comment by westlicht** [comment]
Added new _Play Toggle_ and _Record Toggle_ routing targets. This allow to toggle play/record while still having control on the sequencer. Perfect for foot pedals. This is a good suggestion and I actually ran into this issue before but never bothered fixing it. Will be released with 0.1.40 release.
