### ISSUE TITLE
Using SHIFT+PAGE functions on the Sim in generative mode crashes the app

### ISSUE THREAD

**Issue by knobKompressor** [westlicht/performer#284]
When trying to add a random sequence or euclidean sequence, pressing Shift+Alt (Shift+Page) the sim crashes with an error message "Segmentation fault: 11"

MacOS 10.14.6

**Comment by CedreLo** [comment]
Not on mine

Last OS v0.1.39

**Comment by westlicht** [comment]
Yep, that was a bug. Fixed with next release (or in `master` branch).

**Comment by knobKompressor** [comment]
issue confirmed as resolved, thanks!
