### ISSUE TITLE
Feature Request: Only Velocity in Midi/CV Layout

### ISSUE THREAD

**Issue by Jano1312** [westlicht/performer#299]
In Layout Settings, when in Mode Midi/CV , I want to only select Velocity as CV Output.
In Track Mode, I can only select "Pitch+Vel" under "Voice Config". When selected so, Pitch has always priority in the CV Layout Page.
So I always have to "waste" one CV Output for Pitch to use the Velocity Output per Channel.

Would be nice if we could either only select Velocity in Track Mode under Voice Config, or remove the priority of the Pitch in CV Layout Page.

In my case I want to trigger drums with velocity, but no need for pitch.
And I want to say thank you for this great eurorack sequencer!

**Comment by westlicht** [comment]
Good idea! Will be part of 0.1.41 release.
