### ISSUE TITLE
Feature Request: Sequential Matrix Switch

### ISSUE THREAD

**Issue by ftdBs** [westlicht/performer#326]
Greetings,

Reason for requesting this feature is to be able to come up with musical relationships in time while working with multiple synth voices, without having to use different tracks and inputing notes in them manually, we could rather switch where the musical events are headed. 

On the current system we can set up which physical cv / gate pair is going to receive information from which track but that is fixed for the project (as far as my digging and experiments told me). It would be awesome to be able to do things such as hocketing, round robins and per step channel switching and compose the routings themselves. These would really help having counterpointal effects without really being bach or something :) 

Another place on the sequencer which this could be applied may be CV inputs. It would be awesome to hook up modulation sources and compose which physical output they are going to end up per step, or maybe based on rules.  

The least that can be done to achieve these could be having different routings per pattern (which can not be done at the moment I guess, routings cant change with patterns), then we can make 16 different routings on each pattern and switch those (like in elektron machines we can have completely different settings per pattern, and in midibox seq v4 its possible to  have different midi routings and type of channel and everyting) 

Thanks for reading!
FT

**Comment by westlicht** [comment]
The system is not made to dynamically change output mappings and it probably never will be. A lot of these things can be accomplished with external modules, which is the power of modular. The sequencer should primarily be responsible for sequencing :)
