### ISSUE TITLE
USB TX not sending clock

### ISSUE THREAD

**Issue by Lokua** [westlicht/performer#335]
I don't think MIDI clock is being sent with USB TX like it does with MIDI TX. I have tested with both an Arturia Keystep as well as a Faderfox EC-4 which both receive clock fine from DAW using same cables. Is USB TX expected to send clock info? I am on the v0.1.41 firmware which gave me hope considering it addresses USB issues but no luck for me.

Edit: just tested with a Digitakt and USB TX is working as expected. The only difference I can think of is that the Digitakt is not relying on Performer for power while the Keystep and Faderfox do. I wonder if it could be that clock doesn't work if USB is powering something?

**Comment by westlicht** [comment]
Did you enable USB TX in the clock settings? Instead of testing with other other devices, it's better to use a MIDI monitor application to see if the messages are actually being sent. I would be a bit surprised if clock wasn't sent.

**Comment by westlicht** [comment]
And it definitely has nothing to do with power over usb.

**Comment by Lokua** [comment]
Hello. Sorry for not getting back sooner. Had to have been user error. Thanks for the support :)
