### ISSUE TITLE
User scales loaded from SD card have default name

### ISSUE THREAD

**Issue by weatherfronts** [westlicht/performer#34]
Steps to reproduce:
1. Create a chromatic user scale with a new name (ex: DORIAN)
2. Save this scale to the SD card on an empty slot
3. Load it back from the SD card on any user scale slot
4. The scale structure will be preserved, but the name is not (always INIT)

Expected result: Both name and structure are preserved
Version: 0.1.13

**Comment by westlicht** [comment]
Good catch. As a matter of fact, user scales are currently not written as part of the project at all. All of this will be fixed in the next release, and best of all, existing user scales can still be loaded :)
