### ISSUE TITLE
Transposing Issue?

### ISSUE THREAD

**Issue by ancientbmd** [westlicht/performer#354]
Hello,

 First want to thank you for creating the excellent sequencer! The issue I am having may be just my own lack of understanding. First let me say that I have 2 Westlicht's, and they both act the same. I set up a sequence, then go into routing matrix. I set it to "transpose". All of the cv ins seem to act the same. I have a controller sending volt per octave into a cv in. It does let me transpose, but not like I would like. I am trying to get it to act like a precision adder where a C note on my controller and C note in the sequence would produce a C note in pitch, And also d,e,f, etc. would be their respected pitches. Routing is set to -12  and +12 for the transpose setting. I hope I have not confused you. Any direction you might have is very much appreciated.

Thank You-

**Comment by Lokua** [comment]
Looks like you were able to find the help you were looking for: https://www.modwiggler.com/forum/viewtopic.php?p=3712518#p3712518

Posting here for reference and also I think this signals that the issue can be closed. There are a lot of open issues and I know that can be a demotivator so @westlicht I hope you are doing well.

**Comment by ancientbmd** [comment]
Thanks
