### ISSUE TITLE
Delayed Gates (feat. request)

### ISSUE THREAD

**Issue by SloBloLabs** [westlicht/performer#36]
Would be great if we could make sure the CV output value is available before gates are triggered. I encountered this not to be ensured when programming a certain pattern for BIA.
Current workaround: CV Update Mode = Always and programming the desired CV value in the note slot before (!).

**Comment by westlicht** [comment]
It's something that I could add pretty easily. However, I will first investigate if the the CV outputs are actually behind the gate outputs, because that would be a general problem that would need to be fixed.

**Comment by westlicht** [comment]
I've fixed the update order (no delay yet). Maybe that's all that's necessary. Will be part of the 0.1.15 release.

**Comment by westlicht** [comment]
@SloBloLabs does the problem still exist with the 0.1.15 release?

**Comment by SloBloLabs** [comment]
Simon, sorry for delayed feedback. Please bear with me. Can test the patch tomorrow. ;-)

**Comment by westlicht** [comment]
No worries, let me know if it works, so I can potentially close this ticket.

**Comment by SloBloLabs** [comment]
Hi Simon, thank you for putting effort in this. I reproduced the test case and it is not working yet on 1.15. Using my logic analyzer I could proove that CV is about 900us behind the gate.
Do you know wether the calls to the shift register and the dac are blocking ones? Are there known delays e.g. in the dac to come up with the voltage levels requested?

**Comment by SloBloLabs** [comment]
Will test 1.17 by upcoming weekend.

**Comment by westlicht** [comment]
@SloBloLabs I actually found the bug now. The problem was that the CV update was delayed by one system tick of 1ms. Thanks a lot for reporting this. This is actually a really bad bug to have on a sequencer :D will be fixed with the next 0.1.18 release.

**Comment by SloBloLabs** [comment]
I had 1.18 on the board today. I confirm the gates came closer to the CV updates. I measure 15us time window inbetween, but gates are still hitting before the dac. Trying to fix it by introducing a delay within Engine::update():
    _cvOutput.update();
    for ( uint32_t i=0; i < 168 * 15; ++i) { // 168MHz, 15us
        asm ("nop");
    }
    _gateOutput.update();

It compiles fine, but the sequencer does not come up with this code. Same with
     _cvOutput.update();
    hal::Delay::delay_us(15);
    _gateOutput.update();

Do you have a clue why?

**Comment by westlicht** [comment]
This is weird. I guess I have to measure again, but for me the gates were clearly coming after the CV changes. The delay should work (both your suggestions), does an unchanged version even work?

**Comment by SloBloLabs** [comment]
Yes, sure. It’s just removing my additional lines, recompile and flash. Did this a couple of times today cause I couldn’t belive not being able to introduce such a small change. Need to add I measured with gate and cv connected to Basimilas. Shouldn’t make big difference, though.

**Comment by SloBloLabs** [comment]
Simon, I confirm the issue is closed. The sequencer does exactly what I had in mind now. Thumbs up! Just ignore my previous comment. ;-)

**Comment by westlicht** [comment]
Good to hear, I was a bit surprised at first when I saw your comment but also pretty confident it was all fine :)
