### ISSUE TITLE
Gate outputs does not work at hardware tester.hex...

### ISSUE THREAD

**Issue by Shayshez** [westlicht/performer#37]
I did unnecessary troubleshooting for hours until i checked the sequencer.hex...

**Comment by westlicht** [comment]
Oh crap, that's a regression introduced in release v0.1.15. Really sorry about that! Please use the previous version of the tester which should work fine.

**Comment by Shayshez** [comment]
Never mind, this sequencer worth it.
Thanks for your reply and for one of the best euro sequencer!
