### ISSUE TITLE
MIDI Out

### ISSUE THREAD

**Issue by Shayshez** [westlicht/performer#38]
1. There is few drum machines that respond only to midi channel #10.
Currently it's possible to work only with channes 1-8.
2. There is no sign at the midi monitor page.

**Comment by Shayshez** [comment]
Another midi issue - gates are always short no matter gate length setting.

**Comment by westlicht** [comment]
You can select the midi output channel by holding `SHIFT` and rotating the encoder to select the channel. I should probably change that behaviour and just have the encoder scroll through all the ports/channels. I think this gets people confused , even though it's stated in the manual. Does this solve your issue?

**Comment by Shayshez** [comment]
Yes, i managed to change the midi channel, Thanks!
But there is issue with marged steps, if i set few steps to 100% length, performer sent midi note off after the first step, look at the video:
https://youtu.be/GyKOTGkxiKk

**Comment by westlicht** [comment]
Are you using the latest version?

**Comment by Shayshez** [comment]
Just built it in Thursday and installed v0.1.15, the latest version in the releases page.

**Comment by westlicht** [comment]
Ok, will have a look then.
