### ISSUE TITLE
Glitchy Encoder

### ISSUE THREAD

**Issue by toneburst** [westlicht/performer#4]
I'm finding the encoder glitchy. If turned too fast, it can reverse direction.

I'm using the specified encoder part.

I thought initially it was a hardware issue with my build (I've experienced similar behaviour with other builds, when I've forgotten to solder a capacitor related to the encoder), but a more experienced DIY builder friend noticed the same behaviour with their build.

**Comment by guytaylor** [comment]
Im also getting the same behavior...

_____________________________________



On 20 Mar 2019, at 8:34 PM, alx <notifications@github.com> wrote:

I'm finding the encoder glitchy. If turned too fast, it can reverse
direction.

I'm using the specified encoder part.

I thought initially it was a hardware issue with my build (I've experienced
similar behaviour with other builds, when I've forgotten to solder a
capacitor related to the encoder), but a more experienced DIY builder
friend noticed the same behaviour with their build.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/westlicht/performer/issues/4>, or mute the thread

**Comment by westlicht** [comment]
I actually noticed that behaviour myself a few times, but it rarely bothered me. There are no caps to filter the encoder outputs but there is software debouncing. However, I guess the scan frequency might be too low for certain edge cases. I will investigate.

**Comment by toneburst** [comment]
My impression is that it’s worse when scrolling through lists of items, then when adjusting values.

When calibrating the CV outputs last night, I resorted to using the Next/Previous buttons to move through the list of outputs because using the encoder was unreliable.

However, I don’t recall noticing any issues with the encoder while adjusting the offset values, even when rotating the encoder quite rapidly.

**Comment by toneburst** [comment]
I'm afraid the encoder is still glitchy with 0.1.6. My immediate impression is that it's worse than before, in fact.

As well as reversing direction, now, the selection also sometimes continues to move after I've stopped rotating the encoder.

I will try and shoot a video showing the behaviour this evening.

**Comment by toneburst** [comment]
I should add this is while scrolling through menus. I haven't tested setting individual values with the encoder.

Could it be that the encoder scan-rate is lower when scrolling menus than when setting values?

**Comment by westlicht** [comment]
@toneburst that's odd. Also, you should use 0.1.7 which contains the fix. 0.1.6 did not change anything regarding the encoder. And no, there is no change in scan rate. For me, 0.1.7 works flawlessly now.

**Comment by toneburst** [comment]
I'm really sorry, you're right. I downloaded the 0.1.6 version, thinking that was the most recent, because I hadn't refreshed the Releases page.

Very stupid, I do apologise.

The encoder does seem much better now, thank you. I'm going out now, but will test more thoroughly when I get home this evening.

Really looking forward to testing the MIDI slide behaviour with my MB33 303 clone.

**Comment by westlicht** [comment]
@toneburst no problem, let me know about your findings. Always grateful for feedback!

**Comment by gsmc-alx** [comment]
It's definitely better, but still glitchy.

**Comment by westlicht** [comment]
I guess I need a video. Not glitchy at all for me.

**Comment by toneburst** [comment]
Above comment was me, signed in to my other GitHub account (in case you didn't realise.

I will try and made a video soon.
