### ISSUE TITLE
Dual Drum Track Mode To Use Both CV and Gate Outputs

### ISSUE THREAD

**Issue by toneburst** [westlicht/performer#44]
How about a new Dual track mode, that could use both CV and Gate outputs as drum triggers?

It would have two Gate layers, on for the Gate output, the other would use the CV output of the gate/CV pair as gate/trigger.

**Comment by toneburst** [comment]
Incidentally, I've discovered it's possible to use both Gate and CV outputs of a track as separate triggers for drum voice modules already.

If CV Update Mode is set to Always for the track, it's possible to use high and low note values to trigger drums from the CV output.

It's fiddly, though.

Might be easier if I made a custom scale with only one note in it.

**Comment by westlicht** [comment]
I don't think this is an important feature to be honest. As you mention, it already is possible to do a similar thing by using the note layer as a second trigger layer.
