### ISSUE TITLE
MIDI Track Basic Arpeggiator

### ISSUE THREAD

**Issue by toneburst** [westlicht/performer#47]
A basic tempo-synced arpeggiator option would be really nice for the MIDI>CV track mode.

**Comment by westlicht** [comment]
This was in the back of my head for a while. It will probably get in at some point in the future.

**Comment by toneburst** [comment]
Great! Looking forward to it.

**Comment by toneburst** [comment]
I said “basic”, but obviously, things like play direction and real-time randomisation would be cool, too ;)

I will wait to see what you come up with, anyway.

**Comment by westlicht** [comment]
> I said “basic”, but obviously, things like play direction and real-time randomisation would be cool, too ;)

hehe

**Comment by toneburst** [comment]
Have you dropped this idea entirely, or is it incorporated into a branch you're working on?

**Comment by westlicht** [comment]
It's about to be released.
