### ISSUE TITLE
Generate random or algoritmic population of gates with encoder

### ISSUE THREAD

**Issue by luisonly** [westlicht/performer#48]
I used to own a delptronics triggerman and it has this wonderful function to fill or populate the gates in a sequence. You just turn the knob and it has an algorithm which populates the sequence at the turn of the knob making it more and more complex until it fills it up  This would be amazing for live performance without having to go into the generator menu.

Explanation video:
https://youtu.be/vP50CgGeuhk?t=46
(second 46 shows how the complexity knob works)

**Comment by westlicht** [comment]
You can do a similar thing with the _Gate Probability Bias_ on the track page. Route to that parameter from a CV or MIDI controller and you have a very easy way to change the "complexity" of a sequence while performing. The routing system of PER|FORMER is quite nice for these hands-on things.
