### ISSUE TITLE
Clock swing

### ISSUE THREAD

**Issue by westlicht** [westlicht/performer#5]
Add the option to output the analog clock with swing. This would allow to output the same swing to external sequencers that is also used internally.

**Comment by stansanders** [comment]
seconded, and this would fill a niche that i'm not aware of elsewhere - having the option to output with or without swing.  wmd metron is always with swing, tiptop circadian rhythms is never without swing.  they both have their issues depending on what else is going on, so having the option to do it either way would be a great thing.

**Comment by westlicht** [comment]
part of 0.1.21 release
