### ISSUE TITLE
Add more retriggers? (enhancement)

### ISSUE THREAD

**Issue by Dunk303** [westlicht/performer#50]
Lately I'm thinking about more kind of retriggers. As for now we can set it to 1,2,3 or 4 retriggers for step. Would be cool\useful to add more retriggers per step or different distribution of retriggers...sort of burst generation!
Also actually 3 and 4 retriggers seems to be unequally distributed along the step, is this right?

**Comment by westlicht** [comment]
For the current _note track_ mode I don't have plans to add more retriggers. I had them in the beginning and removed them because I felt they didn't add much (and every bit of data actually counts). I have plans for a new track mode that will be much more flexible in this regard.
