### ISSUE TITLE
Manual Correction: Launchpad track mutes

### ISSUE THREAD

**Issue by sneak-thief** [westlicht/performer#54]
(Version: 0.1.8)

PROBLEM
The launchpad mute command is not documented correctly.

In the manual, it states:

"Launchpad: 
- Sequencer Mode
1 + A - H | Mute/unmute track"

I tried this and it doesn't work.

However, using button 8 instead of 1 works:

8 + A - H | Mute/unmute track

**Comment by westlicht** [comment]
Thanks! Fixed just now.
