### ISSUE TITLE
Alternative Note Off method not supported

### ISSUE THREAD

**Issue by sneak-thief** [westlicht/performer#56]
PROBLEM

The alternate midi Note Off command (Note On + Velocity 0) isn't recognized by the performer and a previously played note stays on. 

"The MIDI Specification says:

"A receiver must be capable of recognizing either method of turning off a note, and should treat them identically." "

https://www.midi.org/forum/228-writing-midi-software-send-note-off,-or-zero-velocity-note-on

I tested this with my Yamaha Montage. 
 

EXPECTED BEHAVIOUR

Sending midi "Note On + Velocity >0" followed by "Note On + Velocity 0" should turn the note/gate off.

**Comment by westlicht** [comment]
Ok, didnt know there are devices not sending note off events. Should be easy to fix.

**Comment by sneak-thief** [comment]
I confirm this fix works. Thank you!
