### ISSUE TITLE
Feature Request: Progress bars for each track's sequence playback on Performer page

### ISSUE THREAD

**Issue by sneak-thief** [westlicht/performer#79]
Issue:
It's currently difficult to get a quick overview of each sequence's playback progress/status, especially in relation to one another.

Enhancement: 
During playback, PAGE: PERFORMER should display sequence "progress bars" (or rotating rings?) in or under each of the Track boxes.  The end of a progress bar would mean the end of the sequence. It would restart along with the sequence looping.

This will provide a much needed summary how all the sequences are currently playing, especially when it comes to polyrhythms and tracks with different divisors.

**Comment by westlicht** [comment]
Will be part of 0.1.21 release.

**Comment by sneak-thief** [comment]
Great news! Very much looking forward to this.

**Comment by sneak-thief** [comment]
Works exactly as I had hoped. Thank you.
