### ISSUE TITLE
Feature Request: Change editing pattern in step mode

### ISSUE THREAD

**Issue by kurtjoy** [westlicht/performer#86]
Not sure if this has been done already, or I'm missing it in the manual (apologies if so). It seems that if you are editing in the step page, you need to jump back into the pattern page to change which pattern is being edited (E1-16). Is there (or can there be a way) to change this directly in the step page?

**Comment by westlicht** [comment]
Thats why one can access the pattern page temporarily. While on the edit page, simply press shift + pattern page and rotate the encoder. When you release the buttons you are back on the edit page.
