### ISSUE TITLE
Midi routing bug

### ISSUE THREAD

**Issue by luisonly** [westlicht/performer#98]
Hi Simon! It appears that when I load a project I lose all the midi routings I had set. Turning it off and on again fixes the problem. 

Thanks for everything man!

**Comment by westlicht** [comment]
This was introduced with when I refactored the routing system to be _non-destructive_. Unfortunately this is a bit of a tricky one. Definitely will fix this as it is a serious bug, thanks for reporting!

**Comment by luisonly** [comment]
Thanks :) It is really needed for live performances in which I have to switch projects!

**Comment by westlicht** [comment]
Fully agree! I have come up with a solution, needs some more testing before releasing it. Expect an update soon.

**Comment by westlicht** [comment]
Will be fixed with 0.1.25.
